const ELASTICSEARCH_INDEX_NAME = 'message';
const ELASTICSEARCH_MAPPING_TYPE_NAME = 'message_mapping';
const ELASTICSEARCH_MAPPING_TYPE = {
  properties: {
    stages: {
      type: 'string',
    },
  },
};

module.exports = {
  ELASTICSEARCH_INDEX_NAME: ELASTICSEARCH_INDEX_NAME,
  ELASTICSEARCH_MAPPING_TYPE_NAME: ELASTICSEARCH_MAPPING_TYPE_NAME,
  ELASTICSEARCH_MAPPING_TYPE: ELASTICSEARCH_MAPPING_TYPE,
};
